version: '3.8'

services:
  npm:
    build:
      context: ./
      dockerfile: npm.Dockerfile
    volumes:
      - ./:/app
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    env_file:
      - ./.env
